// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfzeyvbjzfdstkdcqcgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmemV5dmJqemZkc3RrZGNxY2dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5NzU1MDcsImV4cCI6MjA3NzU1MTUwN30.LUoM1fafGY4mFzR7JgCNOr3hojtOp-MYcSLuVIjd4PU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});